name: CI

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  Awesome_Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npx awesome-lint
